services:
  # ==============================
  # Nginx (Reverse Proxy)
  # ==============================
  nginx:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  # ==============================
  # Laravel (API)
  # ==============================
  php:
    build:
      context: .
      dockerfile: dockerfiles/php/dockerfile
    working_dir: /var/www
    command: >
      sh -c "
      echo 'Aguardando MySQL subir...' &&
      sleep 15 &&
      composer install &&
      php artisan key:generate &&
      php artisan migrate:fresh --seed &&
      exec php-fpm
      "
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  # ==============================
  # MySQL (Database)
  # ==============================
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  # ==============================
  # Shared Resources
  # ==============================
volumes:
  dbdata:

networks:
  app_network:
    driver: bridge
